spring.application.name=plataformamedicos

spring.datasource.url=jdbc:postgresql://localhost:5432/plataformamedicos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=plataforma-medicos-dev-secret-key-change-me-1234567890
security.jwt.expiration-seconds=3600
